apiVersion: v1
kind: ConfigMap
metadata:
  name: traffic-generator-config
  labels:
    kiali-test: traffic-generator-config
data:
  duration: "0s"
  route: http://a/route?path=a,b,c,d,e,f,a;http://a/route?path=a,f,e,d,c,b,a
  rate: "20"
